spring:
  h2:
    console:
      enabled: true
      path: '/console'
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: 'jdbc:h2:file:C:/Users/Kate/Desktop/GIT-repo/todo-spring/todo-spring/todo-app/todo-db'
